# skiminki's computer chess studies
# Copyright (C) 2019 Sami Kiminki
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

BASEDIR:=..

TARGETS:=\
	instructive-compchess-games.pdf \
	tcec-s15-bonus-g2.pdf \
	tcec-s15-sufi-g12.pdf \
	tcec-s16-l2-r23-1.pdf

include $(BASEDIR)/mk/help.mk
include $(BASEDIR)/mk/latex.mk
